import assert from "node:assert/strict";
import test from "node:test";
import Database from "better-sqlite3";
import fs from "node:fs";
import { inspectSqlite, normalizeIndexSql, normalizeTableSql, orderTables } from "../scripts/migrate-sqlite-to-postgres.mjs";

test("normalizes SQLite identity and collation syntax for PostgreSQL", () => {
  const sql = normalizeTableSql(`CREATE TABLE parent (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT UNIQUE COLLATE NOCASE);`);
  assert.match(sql, /GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
  assert.doesNotMatch(sql, /AUTOINCREMENT|COLLATE\s+NOCASE/i);
});

test("orders PostgreSQL tables by foreign-key dependency", () => {
  const ordered = orderTables([
    { name: "child", dependencies: new Set(["parent"]) },
    { name: "parent", dependencies: new Set() },
  ]);
  assert.deepEqual(ordered.map((table) => table.name), ["parent", "child"]);
});

test("inspects a SQLite schema without opening a PostgreSQL connection", () => {
  const source = new Database(":memory:");
  source.exec(`
    CREATE TABLE parent (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL);
    CREATE TABLE child (id INTEGER PRIMARY KEY AUTOINCREMENT, parent_id INTEGER REFERENCES parent(id));
    CREATE INDEX child_parent_idx ON child(parent_id);
    INSERT INTO parent(name) VALUES ('fixture');
    INSERT INTO child(parent_id) VALUES (1);
  `);
  const plan = inspectSqlite(source);
  assert.deepEqual(plan.tables.map((table) => table.name), ["parent", "child"]);
  assert.equal(plan.tables.find((table) => table.name === "parent").rowCount, 1);
  assert.equal(plan.tables.find((table) => table.name === "child").rowCount, 1);
  assert.equal(plan.indexes.length, 1);
  source.close();
});

test("migration importer carries the v26 integrity hardening forward", () => {
  const migration = fs.readFileSync(new URL("../scripts/migrate-sqlite-to-postgres.mjs", import.meta.url), "utf8");
  assert.match(migration, /calendar_events_collab_request_id_fkey/);
  assert.match(migration, /calendar_events_collab_request_idx/);
  assert.match(migration, /schema hardening and collaboration integrity/);
  assert.match(migration, /calendar_events contains orphaned collaboration references/);
});

test("migration importer makes snapshot indexes idempotent", () => {
  const sql = normalizeIndexSql("CREATE UNIQUE INDEX task_assignees_user_idx ON task_assignees(user_id, task_id);");
  assert.match(sql, /^CREATE UNIQUE INDEX IF NOT EXISTS task_assignees_user_idx/);
});
