import { NextResponse } from "next/server";
import { currentUser } from "@/lib/auth";
import db from "@/lib/db";
import { workspacePermission } from "@/lib/workspaces";

export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const user=await currentUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const id=Number((await params).id),permission=workspacePermission(user,id);if(!permission)return NextResponse.json({error:"Forbidden"},{status:403});const workspace=db.prepare("SELECT w.id,w.public_id workspaceKey,w.name,w.kind,w.owner_id ownerId,u.name ownerName FROM workspaces w JOIN users u ON u.id=w.owner_id WHERE w.id=?").get(id),members=db.prepare("SELECT u.id,u.name,u.email,u.avatar,wm.permission FROM workspace_members wm JOIN users u ON u.id=wm.user_id WHERE wm.workspace_id=? ORDER BY u.name COLLATE NOCASE").all(id);return NextResponse.json({workspace,members,permission,canManage:permission==="owner"})}

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const user=await currentUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const id=Number((await params).id);if(workspacePermission(user,id)!=="owner")return NextResponse.json({error:"Forbidden"},{status:403});const{name}=await request.json(),cleanName=String(name||"").trim();if(!cleanName||cleanName.length>80)return NextResponse.json({error:"Invalid workspace name"},{status:400});db.prepare("UPDATE workspaces SET name=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(cleanName,id);return NextResponse.json({ok:true})}

export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){const user=await currentUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const id=Number((await params).id),workspace=db.prepare("SELECT kind FROM workspaces WHERE id=?").get(id) as {kind:string}|undefined;if(workspacePermission(user,id)!=="owner")return NextResponse.json({error:"Forbidden"},{status:403});if(workspace?.kind==="personal")return NextResponse.json({error:"Personal workspaces cannot be deleted"},{status:400});const boardCount=(db.prepare("SELECT COUNT(*) count FROM boards WHERE workspace_id=?").get(id) as {count:number}).count;if(boardCount)return NextResponse.json({error:"Move or delete this workspace's boards first"},{status:409});db.prepare("DELETE FROM workspaces WHERE id=?").run(id);return NextResponse.json({ok:true})}
