"use client";

import { useMemo, useState } from "react";

export type HelpDestination =
  | "board"
  | "my-work"
  | "time"
  | "calendars"
  | "directory"
  | "reminders"
  | "settings";

type HelpTopic = {
  id: string;
  section: string;
  title: string;
  summary: string;
  steps: string[];
  tips?: string[];
  destination?: HelpDestination;
  action?: string;
};

const topics: HelpTopic[] = [
  { id:"start",section:"Getting started",title:"Your Northline workspace",summary:"Learn where your personal work lives and how to move around Northline.",steps:["Use the left sidebar to open Boards, My Work, My Time, Calendars, People, Reminders, Settings, or this Help Center.","Your personal workspace is private by default. Shared workspaces appear in the workspace switcher near the Northline logo.","Use the search field at the top to find tasks across every board you are allowed to access."],tips:["Northline remembers your light or dark theme on this device.","Dates and times automatically use your device time zone."],destination:"board",action:"Open boards" },
  { id:"boards",section:"Boards and tasks",title:"Create and organize a board",summary:"Boards hold tasks, workflow columns, members, and project activity.",steps:["Choose the workspace where the board should live.","Select the plus button beside My Boards and enter a name, description, and optional template.","Use Board, List, Timeline, or Calendar view depending on how you want to work.","Open board settings to rename the board or adjust its details."],tips:["A board starts private. Only people you explicitly share it with can open it.","Board links use long private identifiers; permission checks still apply to every request."],destination:"board",action:"Open boards" },
  { id:"tasks",section:"Boards and tasks",title:"Create, edit, and move tasks",summary:"Track ownership, status, priority, dates, notes, and discussions.",steps:["Select Add task from a board or from a workflow column.","Add a clear title, optional description, priority, tag, due date, and assignee.","Drag a task between columns in Board or List view to change its status.","Open the discussion button on a task card to comment without opening the full editor.","Use Duplicate when a task should become the starting point for another task."],tips:["Only board members appear as assignee choices.","Completed tasks can be hidden automatically using the board's completed-task settings."],destination:"board",action:"Open a board" },
  { id:"columns",section:"Boards and tasks",title:"Customize workflow columns",summary:"Match a board to the way your project actually moves.",steps:["Open the Columns control from the board toolbar.","Add a column, rename it, change its color, or move it into a new position.","Mark the appropriate column as the completed state.","Move tasks out of a column before deleting it, or choose the destination when prompted."],destination:"board",action:"Open boards" },
  { id:"sharing",section:"Sharing and permissions",title:"Share a board",summary:"Invite another Northline user as an editor or viewer.",steps:["Open the board and select Share.","Search the member directory and choose the person you want to add.","Choose Editor if they should change tasks, or Viewer for read-only access.","Return to Share later to change or remove access."],tips:["Sharing a personal board does not expose your other personal boards.","The board owner always retains control of sharing."],destination:"directory",action:"Open People" },
  { id:"workspaces",section:"Sharing and permissions",title:"Use shared workspaces",summary:"Share a collection of boards with the same group of people.",steps:["Open the workspace switcher and choose New shared workspace.","Give the workspace a recognizable name.","Manage the workspace to add members and choose their permission.","Boards created inside it inherit workspace access, while board-specific access can still be managed."],tips:["Your personal workspace cannot be converted into a shared workspace.","Removing workspace access removes inherited access to its boards."],destination:"board",action:"Open workspace switcher" },
  { id:"my-work",section:"Daily work",title:"Use My Work",summary:"See tasks assigned to you across every accessible board.",steps:["Open My Work from the sidebar.","Review open, overdue, due-soon, and completed totals.","Filter or sort the task list to focus on what matters now.","Select a task to jump directly to its board and editor."],destination:"my-work",action:"Open My Work" },
  { id:"reminders",section:"Daily work",title:"Task Buddy reminders",summary:"Receive private Discord reminders for tasks, boards, and collabs.",steps:["Connect Discord to your VTuber Offices identity before using Task Buddy.","Open a task and choose Remind me, or schedule a board-wide reminder from the board toolbar.","Use Reminders to review, change, cancel, retry, or inspect your scheduled reminders.","Accepted collabs automatically remind every accepted member 30 minutes before the event."],tips:["Task reminders are private DMs, not public channel posts.","Board-wide reminders go privately to every member who has linked Discord."],destination:"reminders",action:"Open reminders" },
  { id:"calendars",section:"Calendars and streaming",title:"Create and share calendars",summary:"Keep personal calendars private and share only the schedules you choose.",steps:["Open Calendars and create a calendar with a name, color, time zone, and visibility.","Add standard events, streams, availability windows, or confirmed collabs.","Use calendar members to share a private calendar with specific people.","Choose Public only when you want the schedule available from your People profile."],tips:["Private event details remain protected even when you participate in shared work.","Deleted events stay recoverable in Recently deleted for 30 days."],destination:"calendars",action:"Open calendars" },
  { id:"streams",section:"Calendars and streaming",title:"Publish your stream schedule",summary:"Let teammates see streams or availability without exposing private calendars.",steps:["Create or open a streaming calendar.","Set calendar visibility to Team for Northline members or Public for your People profile.","Add a Scheduled stream with platform, game or category, stream link, and details.","Add Available for collabs when you want other streamers to suggest a collaboration."],destination:"calendars",action:"Open stream schedule" },
  { id:"collabs",section:"Calendars and streaming",title:"Request and manage a collab",summary:"Coordinate a stream with one or several Northline members.",steps:["Open Calendars, then Collab planner, and select Request collab.","Search for and select one or more streamers, choose your calendar, and propose a time.","Invitees can accept, decline, or suggest a new time using their own local time zone.","Any accepted member can propose a reschedule. The new time applies after everyone accepts it.","The organizer can cancel the collab for everyone; all calendar copies and pending reminders are removed."],tips:["Task Buddy privately notifies participants about invitations, responses, reschedules, cancellations, and the automatic 30-minute reminder."],destination:"calendars",action:"Open Collab planner" },
  { id:"time",section:"Time tracking",title:"Track your time",summary:"Use the floating clock or enter a completed time block manually.",steps:["Select the floating clock button from anywhere in Northline.","Start the timer when work begins; it keeps running across page reloads.","Stop the timer when finished and add a useful description if needed.","Open My Time to review entries, add a manual entry, or delete an incorrect entry."],tips:["Times display in your device time zone.","Only you and Northline administrators can see your detailed time card."],destination:"time",action:"Open My Time" },
  { id:"people",section:"People and profiles",title:"Find and contact teammates",summary:"Browse member profiles and public streaming schedules.",steps:["Open People and search by name.","Open a contact card to see the member's email, Discord username when linked, and Northline role.","Choose View public stream schedule when the member has published one."],tips:["Email addresses stay inside the contact card instead of appearing in the main directory grid."],destination:"directory",action:"Open People" },
  { id:"settings",section:"Account and preferences",title:"Preferences, Discord, and sessions",summary:"Manage your personal Northline experience safely.",steps:["Open Settings to confirm your time zone and notification preferences.","Connect Discord through Authentik so Task Buddy can send private reminders and Northline can show your profile picture.","Review active sessions and revoke any session you no longer recognize.","Use the theme control in the top bar to switch between light and dark mode."],tips:["Northline login and Discord linking are separate: Authentik remains your account identity."],destination:"settings",action:"Open settings" },
  { id:"troubleshooting",section:"Troubleshooting",title:"When something does not look right",summary:"Quick checks that solve the most common issues.",steps:["Refresh the page once after a deployment or permission change.","If a shared board is missing, confirm the owner shared the correct board or workspace with your Northline account.","If a Task Buddy DM is missing, confirm Discord is linked and check Reminders for a failed delivery.","If a time looks wrong, allow Northline to synchronize the time zone reported by your browser.","If the problem continues, note what you clicked, the board or calendar name, and any message shown on screen before contacting the site owner."],destination:"settings",action:"Check settings" },
];

export function HelpCenter({ navigate, showWelcome }: { navigate: (destination: HelpDestination) => void; showWelcome: () => void }) {
  const [query,setQuery]=useState("");
  const visible=useMemo(()=>{const q=query.trim().toLocaleLowerCase();return q?topics.filter((topic)=>[topic.section,topic.title,topic.summary,...topic.steps,...(topic.tips||[])].some((value)=>value.toLocaleLowerCase().includes(q))):topics;},[query]);
  const sections=[...new Set(visible.map((topic)=>topic.section))];
  return <div className="help-page">
    <header className="help-hero"><div className="help-hero-heading"><div><span className="eyebrow">NORTHLINE HELP CENTER</span><h1>How can we help?</h1><p>Friendly guides for planning projects, sharing work, scheduling streams, collaborating, and staying on track.</p></div><button className="secondary" onClick={showWelcome}>Show welcome guide</button></div><label className="help-search"><span aria-hidden="true">⌕</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search help topics…" aria-label="Search help topics"/><small>{visible.length} {visible.length===1?"guide":"guides"}</small></label></header>
    {sections.map((section)=><section className="help-section" key={section}><h2>{section}</h2><div className="help-topic-grid">{visible.filter((topic)=>topic.section===section).map((topic)=><details className="help-topic" key={topic.id} id={`help-${topic.id}`}><summary><span><b>{topic.title}</b><small>{topic.summary}</small></span><i>＋</i></summary><div className="help-topic-body"><ol>{topic.steps.map((step)=><li key={step}>{step}</li>)}</ol>{topic.tips?.length?<aside><b>Good to know</b>{topic.tips.map((tip)=><p key={tip}>{tip}</p>)}</aside>:null}{topic.destination&&<button className="secondary" onClick={()=>navigate(topic.destination!)}>{topic.action||"Open feature"}</button>}</div></details>)}</div></section>)}
    {!visible.length&&<div className="help-empty"><b>No guide matched that search</b><p>Try a feature name such as board, reminder, calendar, collab, Discord, or time.</p><button className="secondary" onClick={()=>setQuery("")}>Clear search</button></div>}
  </div>;
}

const welcomeActions: Array<{title:string;copy:string;destination:HelpDestination}> = [
  {title:"Plan work with boards",copy:"Create tasks, customize columns, assign teammates, and share projects.",destination:"board"},
  {title:"See what needs attention",copy:"My Work gathers your assigned tasks from every board.",destination:"my-work"},
  {title:"Schedule streams and collabs",copy:"Publish availability, invite streamers, and coordinate shared events.",destination:"calendars"},
  {title:"Get private reminders",copy:"Task Buddy sends task and collab reminders through Discord DMs.",destination:"reminders"},
  {title:"Track your time",copy:"Run the persistent clock or add time-card entries manually.",destination:"time"},
  {title:"Find your teammates",copy:"Open contact cards and view public streaming schedules.",destination:"directory"},
];

export function WelcomeGuide({name,navigate,openHelp,dismiss}:{name:string;navigate:(destination:HelpDestination)=>void;openHelp:()=>void;dismiss:(remember:boolean)=>void}) {
  const [remember,setRemember]=useState(true);
  return <div className="modal-backdrop welcome-backdrop" role="dialog" aria-modal="true" aria-labelledby="welcome-title"><section className="welcome-guide"><button className="modal-close" onClick={()=>dismiss(remember)} aria-label="Close welcome guide">×</button><div className="welcome-heading"><span className="welcome-mark">N</span><span className="eyebrow">WELCOME TO NORTHLINE</span><h1 id="welcome-title">Hi {name.split(" ")[0]}, let&apos;s get you oriented.</h1><p>Northline brings your projects, stream schedule, collaborations, reminders, and time tracking together. Choose an area to start, or explore the full Help Center.</p></div><div className="welcome-actions">{welcomeActions.map((item)=><button key={item.title} onClick={()=>{navigate(item.destination);dismiss(remember);}}><b>{item.title}</b><span>{item.copy}</span><i>→</i></button>)}</div><footer><label><input type="checkbox" checked={remember} onChange={(event)=>setRemember(event.target.checked)}/> Don&apos;t show this welcome screen again</label><div><button className="secondary" onClick={()=>dismiss(remember)}>Start exploring</button><button className="primary" onClick={()=>{openHelp();dismiss(remember);}}>Open Help Center</button></div></footer></section></div>;
}
