"use client";

import { useEffect, useMemo, useState } from "react";

type Status = "ideas" | "ready" | "progress" | "hold" | "done";
type Task = { id: number; title: string; status: Status; owner: string; due: string; tag: string; priority: "Low" | "Medium" | "High"; comments: number };

const columns: { id: Status; label: string; color: string }[] = [
  { id: "ideas", label: "Ideas", color: "#a78bfa" },
  { id: "ready", label: "Ready", color: "#60a5fa" },
  { id: "progress", label: "In progress", color: "#f59e0b" },
  { id: "hold", label: "On hold", color: "#f472b6" },
  { id: "done", label: "Done", color: "#34d399" },
];

const seed: Task[] = [];
const people: { name:string; user:string; initials:string; role:string; color:string; online:boolean }[] = [];

type WorkspaceUser = { id: number; name: string; email: string; role: "Admin" | "Member" | "Guest"; status: "Active" | "Invited" | "Suspended"; boards: number; initials: string; color: string };
const seedUsers: WorkspaceUser[] = [];

export function OrbitApp() {
  const [tasks, setTasks] = useState<Task[]>(seed);
  const [search, setSearch] = useState("");
  const [view, setView] = useState<"board" | "directory" | "settings" | "admin">("board");
  const [modal, setModal] = useState<"task" | "share" | "reminder" | null>(null);
  const [toast, setToast] = useState("");
  const [sidebar, setSidebar] = useState(true);
  const [dragged, setDragged] = useState<number | null>(null);
  const [taskTitle, setTaskTitle] = useState("");
  const [directoryQuery, setDirectoryQuery] = useState("");
  const [users, setUsers] = useState<WorkspaceUser[]>(seedUsers);
  const [authUser,setAuthUser]=useState<{id:number;name:string;email:string;role:"Admin"|"Member"|"Guest"}|null>(null);
  const [authLoading,setAuthLoading]=useState(true);
  const isAdmin = authUser?.role === "Admin";

  useEffect(() => { localStorage.removeItem("orbit-tasks"); const saved = localStorage.getItem("orbit-tasks-v2"); if (saved) setTasks(JSON.parse(saved)); }, []);
  useEffect(() => { localStorage.setItem("orbit-tasks-v2", JSON.stringify(tasks)); }, [tasks]);
  useEffect(()=>{fetch("/api/auth/me").then(r=>r.json()).then(d=>setAuthUser(d.user)).finally(()=>setAuthLoading(false))},[]);
  useEffect(()=>{if(!isAdmin)return;fetch("/api/admin/users").then(r=>r.json()).then(d=>{if(d.users)setUsers(d.users.map((u:any)=>({...u,boards:0,initials:u.name.split(" ").map((x:string)=>x[0]).join("").slice(0,2).toUpperCase(),color:u.role==="Admin"?"#7961e8":u.role==="Member"?"#2f9dde":"#ef9d31"})))})},[isAdmin]);
  const filtered = useMemo(() => tasks.filter(t => t.title.toLowerCase().includes(search.toLowerCase())), [tasks, search]);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2800); };
  const addTask = () => { if (!taskTitle.trim()) return; setTasks([...tasks, { id: Date.now(), title: taskTitle, status: "ideas", owner: "JM", due: "No date", tag: "General", priority: "Medium", comments: 0 }]); setTaskTitle(""); setModal(null); notify("Task added to Ideas"); };

  if(authLoading)return <div className="auth-screen"><div className="auth-card"><div className="auth-brand"><div className="brand-mark">O</div>orbit</div><p>Opening your workspace…</p></div></div>;
  if(!authUser)return <Login onLogin={setAuthUser}/>;
  return <div className="app-shell">
    <aside className={sidebar ? "sidebar" : "sidebar collapsed"}>
      <div className="brand"><div className="brand-mark">O</div><span>orbit</span><button className="icon-button close-side" onClick={() => setSidebar(false)}>‹</button></div>
      <button className="workspace"><span className="workspace-icon">W</span><span><b>My Workspace</b><small>Private workspace</small></span><i>⌄</i></button>
      <nav>
        <button className={view === "board" ? "active" : ""} onClick={() => setView("board")}><span>⌂</span> Home</button>
        <button><span>◎</span> My work <em>5</em></button>
        <button className={view === "directory" ? "active" : ""} onClick={() => setView("directory")}><span>♙</span> People</button>
      </nav>
      <div className="nav-label"><span>MY BOARDS</span><button>＋</button></div>
      <nav className="boards"><button className={view === "board" ? "active" : ""} onClick={() => setView("board")}><i className="dot purple"/>New Board</button></nav>
      <div className="nav-label"><span>SHARED WITH ME</span></div>
      <nav className="boards"><span className="nav-empty">No shared boards</span></nav>
      <div className="sidebar-bottom">{isAdmin && <button className={view === "admin" ? "admin-nav active" : "admin-nav"} onClick={() => setView("admin")}><span>♜</span> Administration <em>Admin</em></button>}<button onClick={() => setView("settings")}><span>⚙</span> Settings</button><button><span>?</span> Help & feedback</button><div className="profile"><Avatar initials={authUser.name.split(" ").map(x=>x[0]).join("").slice(0,2)} color="#8b5cf6"/><span><b>{authUser.name}</b><small>{authUser.role}</small></span><button aria-label="Sign out" title="Sign out" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});setAuthUser(null)}}>↪</button></div></div>
    </aside>

    <main className="main">
      <header className="topbar">{!sidebar && <button className="icon-button" onClick={() => setSidebar(true)}>☰</button>}<div className="global-search">⌕<input placeholder="Search anything…" value={search} onChange={e => setSearch(e.target.value)}/><kbd>⌘ K</kbd></div><div className="top-actions"><button className="icon-button">◔<i/></button><button className="icon-button">♧</button><Avatar initials="JM" color="#8b5cf6"/></div></header>
      {view === "board" && <BoardView tasks={filtered} setTasks={setTasks} onAdd={() => setModal("task")} onShare={() => setModal("share")} onReminder={() => setModal("reminder")} dragged={dragged} setDragged={setDragged}/>} 
      {view === "directory" && <Directory query={directoryQuery} setQuery={setDirectoryQuery} onInvite={() => { notify("Invite copied to clipboard"); }}/>} 
      {view === "settings" && <Settings notify={notify}/>} 
      {view === "admin" && isAdmin && <Admin users={users} setUsers={setUsers} notify={notify}/>} 
    </main>
    {modal && <Modal type={modal} close={() => setModal(null)} taskTitle={taskTitle} setTaskTitle={setTaskTitle} addTask={addTask} notify={notify}/>} 
    {toast && <div className="toast"><b>✓</b>{toast}</div>}
  </div>;
}

function Login({onLogin}:{onLogin:(u:any)=>void}){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();setBusy(false);if(!r.ok)setError(d.error||'Sign in failed');else onLogin(d.user)};return <div className="auth-screen"><div className="auth-aside"><div className="auth-brand light"><div className="brand-mark">O</div>orbit</div><div><span>PROJECTS IN MOTION</span><h1>One calm place for your whole community.</h1><p>Plan launches, coordinate collaborators, and keep everyone moving in the same direction.</p></div><small>Self-hosted · Private by design</small></div><form className="auth-card login-card" onSubmit={submit}><div className="auth-brand"><div className="brand-mark">O</div>orbit</div><div className="login-copy"><span>WELCOME BACK</span><h2>Sign in to your workspace</h2><p>Use your community identity or the emergency local account.</p></div>{error&&<div className="auth-error">{error}</div>}<a className="primary wide" href="/api/auth/oidc/start">Sign in with Authentik</a><div className="login-help">Or use the emergency local administrator login.</div><label>Username or email<input type="text" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Username or email"/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password"/></label><button className="wide" disabled={busy}>{busy?'Signing in…':'Local sign in'}</button></form></div>}

function Avatar({ initials, color }: { initials: string; color: string }) { return <span className="avatar" style={{ background: color }}>{initials}</span>; }

function BoardView({ tasks, setTasks, onAdd, onShare, onReminder, dragged, setDragged }: any) {
  return <section className="content board-page"><div className="board-head"><div><div className="eyebrow">MY WORKSPACE <span>/</span> BOARDS</div><h1>New Board <button>☆</button></h1><p>Add your first tasks and shape a workflow that fits your team.</p></div><div className="head-actions"><button className="secondary" onClick={onShare}>♙ Share</button><button className="primary" onClick={onAdd}>＋ Add task</button></div></div>
    <div className="board-tabs"><button className="active">▦ Board</button><button>☷ List</button><button>▥ Timeline</button><button>▣ Calendar</button><span/><button>⌁ Filter</button><button>⇅ Sort</button><button>•••</button></div>
    <div className="board-stats"><span><b>{tasks.length}</b> tasks</span><span><b>{tasks.filter((t:Task)=>t.status==="done").length}</b> completed</span><div className="progress"><i style={{width:`${Math.round(tasks.filter((t:Task)=>t.status==="done").length / Math.max(tasks.length,1)*100)}%`}}/></div><strong>{Math.round(tasks.filter((t:Task)=>t.status==="done").length / Math.max(tasks.length,1)*100)}%</strong><button className="reminder-link" onClick={onReminder}>◷ Set Discord reminder</button></div>
    <div className="kanban">{columns.map(col => <div className="column" key={col.id} onDragOver={e=>e.preventDefault()} onDrop={() => { if (dragged) setTasks((old:Task[])=>old.map(t=>t.id===dragged?{...t,status:col.id}:t)); setDragged(null); }}><div className="column-head"><span style={{background:col.color}}/>{col.label}<em>{tasks.filter((t:Task)=>t.status===col.id).length}</em><button>•••</button></div><div className="cards">{tasks.filter((t:Task)=>t.status===col.id).map((task:Task)=><TaskCard key={task.id} task={task} setDragged={setDragged}/>)}</div><button className="add-inline" onClick={onAdd}>＋ Add task</button></div>)}</div>
  </section>;
}

function TaskCard({ task, setDragged }: { task: Task; setDragged: (id:number)=>void }) { return <article className="task-card" draggable onDragStart={()=>setDragged(task.id)}><div className="card-top"><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span><button>•••</button></div><h3>{task.title}</h3><span className="tag">{task.tag}</span><div className="card-foot"><Avatar initials={task.owner} color={task.owner==="JM"?"#8b5cf6":task.owner==="AK"?"#ec4899":"#0ea5e9"}/><span className="due">◷ {task.due}</span><span className="comments">◌ {task.comments}</span></div></article>; }

function Directory({query,setQuery,onInvite}:any) { const list=people.filter(p=>(p.name+p.user).toLowerCase().includes(query.toLowerCase())); return <section className="content directory"><div className="page-title"><div><div className="eyebrow">MY WORKSPACE</div><h1>People</h1><p>Find teammates and manage workspace access.</p></div><button className="primary" onClick={onInvite}>＋ Invite people</button></div><div className="directory-tools"><div className="global-search">⌕<input placeholder="Search people by name or username…" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="secondary">All roles⌄</button></div><div className="people-grid">{list.map(p=><article className="person" key={p.user}><Avatar initials={p.initials} color={p.color}/><i className={p.online?"online":""}/><h3>{p.name}</h3><p>{p.user}</p><span>{p.role}</span><button className="secondary">View profile</button></article>)}</div>{!list.length&&<div className="empty-state"><b>No people yet</b><span>An administrator can create the first workspace member.</span></div>}</section>; }

function Admin({ users, setUsers, notify }: { users: WorkspaceUser[]; setUsers: React.Dispatch<React.SetStateAction<WorkspaceUser[]>>; notify: (s:string)=>void }) {
  const [tab,setTab]=useState<"users"|"boards"|"audit"|"security">("users"); const [query,setQuery]=useState(""); const [showCreate,setShowCreate]=useState(false); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [role,setRole]=useState<WorkspaceUser["role"]>("Member");
  const shown=users.filter(u=>(u.name+u.email+u.role).toLowerCase().includes(query.toLowerCase()));
  const createUser=async()=>{if(!name.trim()||!email.trim()||password.length<10)return;const r=await fetch('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,role,password})});if(!r.ok){notify((await r.json()).error||'Could not create user');return}const initials=name.split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase();setUsers([...users,{id:(await r.json()).id,name,email,role,status:"Active",boards:0,initials,color:"#6d5bd0"}]);setName("");setEmail("");setPassword("");setShowCreate(false);notify(`Account created for ${name}`)};
  const toggleStatus=async(id:number)=>{const user=users.find(u=>u.id===id);if(!user)return;const status=user.status==="Suspended"?"Active":"Suspended";const r=await fetch(`/api/admin/users/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});if(r.ok)setUsers(users.map(u=>u.id===id?{...u,status}:u));};
  return <section className="content admin-page"><div className="admin-banner"><div><span className="admin-kicker">ADMIN CONSOLE</span><h1>Workspace administration</h1><p>Control members, access, security, and workspace-wide activity.</p></div><div className="shield">♜</div></div>
    <div className="metric-grid"><div><span>WORKSPACE MEMBERS</span><b>{users.length}</b><small><i className="up">↑ 1</i> this month</small></div><div><span>ACTIVE BOARDS</span><b>5</b><small>Across 3 teams</small></div><div><span>ADMINS</span><b>{users.filter(u=>u.role==="Admin").length}</b><small>Full workspace access</small></div><div><span>PENDING INVITES</span><b>{users.filter(u=>u.status==="Invited").length}</b><small>Awaiting sign-in</small></div></div>
    <div className="admin-panel"><div className="admin-tabs"><button className={tab==="users"?"active":""} onClick={()=>setTab("users")}>Users</button><button className={tab==="boards"?"active":""} onClick={()=>setTab("boards")}>Board access</button><button className={tab==="audit"?"active":""} onClick={()=>setTab("audit")}>Audit log</button><button className={tab==="security"?"active":""} onClick={()=>setTab("security")}>Security</button></div>
    {tab==="users"&&<><div className="admin-toolbar"><div className="global-search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search users, emails, or roles…"/></div><button className="secondary">⇩ Export</button><button className="primary" onClick={()=>setShowCreate(true)}>＋ Create user</button></div><div className="user-table"><div className="table-row table-head"><span>User</span><span>Role</span><span>Status</span><span>Board access</span><span>Last active</span><span/></div>{shown.map((u,i)=><div className="table-row" key={u.id}><div className="user-cell"><Avatar initials={u.initials} color={u.color}/><span><b>{u.name}</b><small>{u.email}</small></span></div><span className={`role-pill ${u.role.toLowerCase()}`}>{u.role}</span><span className={`status-pill ${u.status.toLowerCase()}`}>● {u.status}</span><span>{u.boards} {u.boards===1?"board":"boards"}</span><span className="muted">{i===0?"Now":i===1?"12 min ago":i===2?"Yesterday":"Never"}</span><div className="row-menu"><button title={u.id===1?"The primary admin cannot be suspended":"Suspend or reactivate user"} disabled={u.id===1} onClick={()=>{toggleStatus(u.id);notify(u.status==="Suspended"?"User reactivated":"User suspended")}}>•••</button></div></div>)}</div></>}
    {tab==="boards"&&<div className="admin-section"><div className="section-copy"><h2>Board access overview</h2><p>Review ownership and visibility across every workspace board.</p></div><div className="empty-state"><b>No board access records</b><span>Access assignments will appear after boards are created and shared.</span></div></div>}
    {tab==="audit"&&<div className="admin-section"><div className="section-copy"><h2>Recent workspace activity</h2><p>An immutable record of administrative and access events.</p></div><div className="empty-state"><b>No administrative activity</b><span>New account and access events will be recorded here.</span></div></div>}
    {tab==="security"&&<div className="admin-section security-grid"><div className="security-item"><span className="security-icon">⌁</span><div><h3>Invite-only registration</h3><p>Only admins can create accounts and send invitations.</p></div><label className="switch"><input type="checkbox" defaultChecked/><i/></label></div><div className="security-item"><span className="security-icon">◫</span><div><h3>Require Discord connection</h3><p>Members must link a Discord account after first sign-in.</p></div><label className="switch"><input type="checkbox"/><i/></label></div><div className="security-item"><span className="security-icon">◴</span><div><h3>Session timeout</h3><p>Automatically sign members out after inactivity.</p></div><select><option>7 days</option><option>24 hours</option><option>30 days</option></select></div><div className="security-item"><span className="security-icon">⚿</span><div><h3>Recovery access</h3><p>Local owner account is available if Discord is offline.</p></div><span className="status-pill active">● Enabled</span></div></div>}
    </div>{showCreate&&<div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={()=>setShowCreate(false)}>×</button><span className="modal-icon purple-bg">♙</span><h2>Create workspace user</h2><p>Only administrators can create users. Share the temporary password securely.</p><label>Full name<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Taylor Morgan"/></label><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="taylor@example.com"/></label><label>Temporary password<input type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 10 characters"/></label><label>Workspace role<select value={role} onChange={e=>setRole(e.target.value as WorkspaceUser["role"])}><option>Member</option><option>Guest</option><option>Admin</option></select></label><div className="permission-note"><b>{role}</b><span>{role==="Admin"?"Can manage users, boards, integrations, and security.":role==="Member"?"Can create boards and collaborate where granted access.":"Can only access boards explicitly shared with them."}</span></div><button className="primary wide" onClick={createUser}>Create user</button></div></div>}</section>;
}

function Settings({notify}:{notify:(s:string)=>void}) { const [connected,setConnected]=useState(false); return <section className="content settings"><div className="page-title"><div><div className="eyebrow">WORKSPACE SETTINGS</div><h1>Integrations</h1><p>Connect your community tools and decide where Orbit sends updates.</p></div></div><div className="settings-card"><div className="discord-logo">☁</div><div><h2>Discord</h2><p>Link sign-in, members, and task reminders to your Discord server.</p></div><span className={connected?"connected":"not-connected"}>{connected?"● Connected":"Not connected"}</span></div><div className="settings-body"><div><h3>Discord account</h3><p>Use Discord as your primary identity. Local owner access remains available as a recovery option.</p></div><button className={connected?"secondary":"discord-button"} onClick={()=>{setConnected(!connected);notify(connected?"Discord disconnected":"Discord server connected")}}>{connected?"Disconnect":"Connect Discord"}</button></div><div className="settings-body"><div><h3>Bot reminders</h3><p>Send scheduled task reminders to channels the bot can access.</p><div className="channel-preview"><span>#</span><b>project-updates</b><small>Default reminder channel</small></div></div><button className="secondary" onClick={()=>notify("Bot configuration saved")}>Configure bot</button></div><div className="settings-body"><div><h3>Local sign-in</h3><p>Password access is enabled for one workspace owner. Invite-only registration is recommended.</p></div><span className="connected">● Enabled</span></div></section>; }

function Modal({type,close,taskTitle,setTaskTitle,addTask,notify}:any) { return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal"><button className="modal-close" onClick={close}>×</button>{type==="task"&&<><span className="modal-icon purple-bg">＋</span><h2>Create a task</h2><p>Add a new item to the Ideas column.</p><label>Task name<input autoFocus value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")addTask()}} placeholder="What needs to be done?"/></label><div className="modal-row"><label>Status<select><option>Ideas</option><option>Ready</option><option>In progress</option></select></label><label>Priority<select><option>Medium</option><option>High</option><option>Low</option></select></label></div><button className="primary wide" onClick={addTask}>Create task</button></>}{type==="share"&&<><span className="modal-icon blue-bg">♙</span><h2>Share New Board</h2><p>Give a workspace member access to this board.</p><label>Search people<input autoFocus placeholder="Name or username"/></label><div className="empty-state"><b>No members available</b><span>Create workspace users from Administration first.</span></div><button className="primary wide" disabled>Share board</button></>}{type==="reminder"&&<><span className="modal-icon discord-bg">#</span><h2>Schedule Discord reminder</h2><p>Send a board update through your server bot.</p><label>Channel<select disabled><option>No channels configured</option></select></label><div className="modal-row"><label>Date<input type="date"/></label><label>Time<input type="time"/></label></div><label>Message<textarea placeholder="Write a reminder message…"/></label><button className="discord-button wide" onClick={()=>{close();notify("Connect Discord before scheduling reminders")}}>Schedule reminder</button></>}</div></div>; }
