import { NextResponse } from "next/server";
import { currentUser } from "@/lib/auth";
import db from "@/lib/db";
import { boardPermission,canEdit } from "@/lib/boards";

const statuses=["ideas","ready","progress","hold","done"],priorities=["Low","Medium","High"];
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){
  const user=await currentUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const id=Number((await params).id),task=db.prepare("SELECT board_id FROM tasks WHERE id=?").get(id) as {board_id:number}|undefined;if(!task)return NextResponse.json({error:"Not found"},{status:404});if(!canEdit(boardPermission(user,task.board_id)))return NextResponse.json({error:"Forbidden"},{status:403});
  const body=await request.json();if(body.title!==undefined&&!String(body.title).trim())return NextResponse.json({error:"Task title is required"},{status:400});if(body.title&&String(body.title).length>200||body.description&&String(body.description).length>5000||body.tag&&String(body.tag).length>50||body.status&&!statuses.includes(body.status)||body.priority&&!priorities.includes(body.priority))return NextResponse.json({error:"Invalid task details"},{status:400});
  if(body.assignee_id){const allowed=db.prepare("SELECT 1 FROM users u JOIN boards b ON b.id=? LEFT JOIN board_members bm ON bm.board_id=b.id AND bm.user_id=u.id WHERE u.id=? AND u.status='Active' AND (u.id=b.owner_id OR bm.user_id IS NOT NULL)").get(task.board_id,Number(body.assignee_id));if(!allowed)return NextResponse.json({error:"Assignee does not have access to this board"},{status:400});}
  const allowed=["title","description","status","priority","tag","due_date","assignee_id"] as const;const update=db.transaction(()=>{for(const key of allowed)if(Object.prototype.hasOwnProperty.call(body,key))db.prepare(`UPDATE tasks SET ${key}=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(body[key],id);db.prepare("UPDATE boards SET updated_at=CURRENT_TIMESTAMP WHERE id=?").run(task.board_id);db.prepare("INSERT INTO audit_log(actor_id,action,target) VALUES(?,?,?)").run(user.id,"TASK.UPDATE",String(id));});update();return NextResponse.json({ok:true});
}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){const user=await currentUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const id=Number((await params).id),task=db.prepare("SELECT board_id FROM tasks WHERE id=?").get(id) as {board_id:number}|undefined;if(!task)return NextResponse.json({error:"Not found"},{status:404});if(!canEdit(boardPermission(user,task.board_id)))return NextResponse.json({error:"Forbidden"},{status:403});db.transaction(()=>{db.prepare("DELETE FROM tasks WHERE id=?").run(id);db.prepare("INSERT INTO audit_log(actor_id,action,target) VALUES(?,?,?)").run(user.id,"TASK.DELETE",String(id));})();return NextResponse.json({ok:true});}
