import { NextResponse } from "next/server";
import { currentUser } from "@/lib/auth";
import db from "@/lib/db";
import { boardPermission,canEdit,canShare } from "@/lib/boards";

export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const user=await currentUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const id=Number((await params).id),permission=boardPermission(user,id);if(!permission)return NextResponse.json({error:"Forbidden"},{status:403});const board=db.prepare("SELECT id,name,description,owner_id ownerId FROM boards WHERE id=?").get(id);const tasks=db.prepare(`SELECT t.id,t.title,t.description,t.status,t.priority,t.tag,t.due_date due,u.id ownerId,u.name ownerName,
  (SELECT COUNT(*) FROM comments c WHERE c.task_id=t.id) comments FROM tasks t LEFT JOIN users u ON u.id=t.assignee_id WHERE t.board_id=? ORDER BY t.created_at`).all(id);const members=db.prepare("SELECT u.id,u.name,u.email,bm.permission FROM board_members bm JOIN users u ON u.id=bm.user_id WHERE bm.board_id=? ORDER BY u.name").all(id);return NextResponse.json({board,tasks,members,permission,canEdit:canEdit(permission),canShare:canShare(permission)});}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const user=await currentUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const id=Number((await params).id);if(!canShare(boardPermission(user,id)))return NextResponse.json({error:"Forbidden"},{status:403});const{name,description}=await request.json();db.prepare("UPDATE boards SET name=COALESCE(?,name),description=COALESCE(?,description),updated_at=CURRENT_TIMESTAMP WHERE id=?").run(name?.trim()||null,description??null,id);return NextResponse.json({ok:true});}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){const user=await currentUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const id=Number((await params).id),permission=boardPermission(user,id);if(permission!=="owner"&&permission!=="admin")return NextResponse.json({error:"Forbidden"},{status:403});db.prepare("DELETE FROM boards WHERE id=?").run(id);return NextResponse.json({ok:true});}
